---
- name: Connecting to Leaf
  hosts: ceos3
  connection: local
  gather_facts: false

  tasks:

    - name: Correct Interfaces
      arista.eos.eos_interfaces:
        config:
         - name: Ethernet3
           enabled: true
